services:
  stac_fastapi_eodag_server:
    image: stac-fastapi-eodag:latest
    container_name: eodag_server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318/"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-config.yml"]
    container_name: otel_collector
    restart: unless-stopped
    volumes:
      - ./config/otelcol_config.yml:/etc/otelcol-config.yml
    ports:
      - "4318:4318"
      - "8000:8000"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
