services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ./config/otelcol_config.yml:/etc/otelcol-config.yml
    ports:
      - "4318:4318"   # OTLP HTTP
      - "8000:8000"   # Prometheus metrics
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14318:4318"   # OTLP HTTP
